export const Civs = {
    "civ5-vanilla": [
        "America",
        "Arabia",
        "Assyria",
        "Austria",
        "The Aztecs",
        "Babylon",
        "Brazil",
        "Byzantium",
        "Carthage",
        "The Celts",
        "China",
        "Denmark",
        "Netherlands",
        "Egypt",
        "England",
        "Ethiopia",
        "France",
        "Germany",
        "Greece",
        "The Huns",
        "The Inca",
        "India",
        "Indonesia",
        "The Iroquois",
        "Japan",
        "Korea",
        "The Maya",
        "Mongolia",
        "Morocco",
        "The Ottomans",
        "Persia",
        "Poland",
        "Polynesia",
        "Portugal",
        "Rome",
        "Russia",
        "The Shoshone",
        "Siam",
        "Songhai",
        "Spain",
        "Sweden",
        "Mali",
        "The Zulu",
    ],

    lekmod: [
        'Akkad',
        'Akzum',
        'Argentina',
        'Armenia',
        'Australia',
        'Ayyubids',
        'Belgium',
        'Boers',
        'Bolivia',
        'Brunei',
        'Bulgaria',
        'Burma',
        'Canada',
        'Chile',
        'Colombia',
        'Cuba',
        'Finland',
        'Franks',
        'Gauls',
        'Georgia',
        'Golden Horde',
        'Goths',
        'Hittites',
        'Hungary',
        'Ireland',
        'Israel',
        'Italy',
        'Jerusalem',
        'Khmer',
        'Kilwa',
        'Kongo',
        'Lithuania',
        'Macedonia',
        'Madagascar',
        'Manchuria',
        'The Maori',
        'Maurya',
        'Mexico',
        'Moors',
        'Mysore',
        'Nabatea',
        'New Zealand',
        'Normandy',
        'Norway',
        'Nubia',
        'Oman',
        'Palmyra',
        'Papal State',
        'Pheonicia',
        'Philippines',
        'Prussia',
        'Romania',
        'Scotland',
        'Sioux',
        'Sumeria',
        'Switzerland',
        'Tibet',
        'Timurids',
        'Tonga',
        'Turkey',
        'U.A.E',
        'Ukraine',
        'Vatican',
        'Venice',
        'Vietnam',
        'Wales',
        'Yugoslavia',
        'Zimbabwe'
    ],

    "civ6-vanilla": [
        'Catherine de Medici',
        'Cleopatra',
        'Frederick Barbarossa',
        'Gandhi',
        'Gilgamesh',
        'Gorgo',
        'Harald Hardrada',
        'Hojo Tokimune',
        'Julius Caesar',
        'Montezuma',
        'Mvemba a Nzinga',
        'Pedro II',
        'Pericles',
        'Peter',
        'Philip II',
        'Qin Shi Huang',
        'Saladin',
        'Teddy Roosevelt',
        'Tomyris',
        'Trajan',
        'Victoria'
    ],

    "civ6-rnf": [
        'Chandragupta',
        'Genghis Khan',
        'Lautaro',
        'Poundmaker',
        'Robert the Bruce',
        'Seondeok',
        'Shaka',
        'Tamar',
        'Wilhelmina'
    ],

    "civ6-gs": [
        'Dido',
        'Eleanor of Aquitaine (England)',
        'Eleanor of Aquitaine (France)',
        'Kristina',
        'Kupe',
        'Mansa Musa',
        'Matthias Corvinus',
        'Pachacuti',
        'Suleiman',
        'Wilfred Laurier'
    ],

    "civ6-frontier": [
        'Ambiorix',
        'Basil II',
        'Bà Triệu',
        'Hammurabi',
        'João III',
        'Kublai Khan (China)',
        'Kublai Khan (Mongolia)',
        'Lady Six Sky',
        'Menelik II',
        'Simón Bolívar'
    ],

    "civ6-leaderpass": [
        'Abraham Lincoln',
        'Cleopatra (Ptolemaic)',
        'Elizabeth I',
        'Harald Hardrada (Varangian)',
        'Ludwig II',
        'Nader Shah',
        'Nzinga Mbande',
        'Qin Shi Huang (Unifier)',
        'Ramses II',
        'Saladin (Sultan)',
        'Sejong',
        'Suleiman (Muhtesem)',
        'Sundiata Keita',
        'Theodora',
        'Tokugawa',
        'Victoria (Age of Steam)',
        'Wu Zetian',
        'Yongle'
    ],

    "civ6-extra": [
        'Alexander',
        'Amanitore',
        'Cyrus',
        'Gitarja',
        'Jadwiga',
        'Jayavarman VII',
        'John Curtin'
    ],

    "civ6-personas": [
        "Catherine de Medici (Magnificence)",
        "Teddy Roosevelt (Rough Rider)"
    ]
};
