name: Build and test Docker image

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Get version number from package.json
              id: version
              run:  echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and test
              uses: docker/build-push-action@v4.0.0
              with:
                  # List of tags
                  tags: civbot:test
                  target: test
            - name: Publish docker image
              # You may pin to the exact commit or the version.
              # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              uses: docker/build-push-action@v4.0.0
              if: ${{ endsWith(github.ref, '/master') }} # only push on master
              with:
                  # Push is a shorthand for --output=type=registry
                  push: true
                  # List of tags
                  tags: ghcr.io/jpjarvis/civbot:${{steps.version.outputs.version}}-${{github.run_number}}
                  target: production
