name: Release CivBot

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Git
              run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
            - name: Get version number from package.json 
              id: version
              run:  echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish docker image
              # You may pin to the exact commit or the version.
              # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              uses: docker/build-push-action@v4.0.0
              with:
                  # Push is a shorthand for --output=type=registry
                  push: true
                  # List of tags
                  tags: ghcr.io/jpjarvis/civbot:${{steps.version.outputs.version}}
                  target: production
            - name: Tag the new version
              run: |
                TAG=v${{steps.version.outputs.version}}
                git tag $TAG
                git push origin $TAG
            - name: Increment version
              run: ./increment-version.sh
            - name: Commit and push version bump
              run: |
                git add -A
                git commit -m "Increment version number"
                git push
